version: '3.7'

services:
  web-app:
    container_name: slot-machine
    image: node:12.14.0
    restart: always
    working_dir: /usr/app/
    volumes:
      - .:/usr/app/
    ports:
      - '3000:3000'
    command:  sh -c 'npm i && npm run build && npm start'
    # command:  sh -c 'npm i && npm i -g now && now dev'
